= Setting up Neo4j for Spatial Queries (in progress)
//^

:hp-tags: Neo4j, neo4j-spatial, Installation, Configuration
//^

IMPORTANT: *BLOG POST INCOMPLETE, STILL IN PROGRESS*

TIP: link:http://legis-graph.github.io/legis-graph-spatial/[Here's an example application] issuing spatial queries to Neo4j and the link:https://neo4j.com/blog/geospatial-indexing-us-congress-neo4j/[associated blog post].

CAUTION: The following assumptions are made: You have a version of link:https://neo4j.com/download/other-releases/[Neo4j 3.x] installed. You are familiar with link:http://neo4j.com/docs/developer-manual/current/get-started/#cypher-getting-started[the Cypher Query Language ("Ascii art for graph databases")].

.Installation of neo4j-spatial
. Create a plugins folder within your Neo4j database location. In my case this was
`/Users/trycrmr/Documents/Neo4j/3.0.3/spatialPlaytime/plugins`.
. Download the appropriate version of the link:https://github.com/neo4j-contrib/spatial[neo4j-spatial] plugin for your 3.x version of Neo4j. This is likely a zipped up .jar file.
. unzip the .jar file and put it in the plugins directory created earlier. The full path to my neo4j-spatial .jar file is `/Users/trycrmr/Documents/Neo4j/3.0.3/spatialPlaytime/plugins/neo4j-spatial-0.19-neo4j-3.0.3-server-plugin.jar`.
. Restart your Neo4j server
. Issuing the following cypher query to Neo4j lists the procedures available to you now that the neo4j-spatial plugin is installed: `CALL spatial.procedures`
.. *Note*: There is no documentation for the these procedures yet, but insights can be drawn (such as what parameters can be passed to the procedures) from link:https://github.com/neo4j-contrib/spatial/blob/master/src/main/java/org/neo4j/gis/spatial/procedures/SpatialProcedures.java[the code] at this time. For example, the parameters for the `spatial.withinDistance` are listed in the code below (hint: `@Name`)

[source,java]
----
    @Procedure("spatial.withinDistance")
    @PerformsWrites // TODO FIX
    public Stream<NodeDistanceResult> findGeometriesWithinDistance(
            @Name("layerName") String name,
            @Name("coordinate") Object coordinate,
            @Name("distanceInKm") double distanceInKm) {

        Layer layer = getLayerOrThrow(name);
        return GeoPipeline
                .startNearestNeighborLatLonSearch(layer, toCoordinate(coordinate), distanceInKm)
                .sort(DISTANCE)
                .stream().map(r -> {
                    double distance = r.hasProperty(DISTANCE) ? ((Number) r.getProperty(DISTANCE)).doubleValue() : -1;
                    return new NodeDistanceResult(r.getGeomNode(), distance);
                });
    }
----
//^ 

NOTE: No data is imported by this plugin. Each map layer can be created by pointing the appropriate procedure at a shapefile. 

.Importing a Map Layer
. Find the mapping data (i.e. Shapefiles) of the area you would like your graph database to map. In this case we will use link:https://hiu.state.gov/data/data.aspx[Shapefiles provided by the U.S. State Department].
.. Of note: The download will contain several files. We will need all of them. 
. One of the procedures neo4j-spatial provides (as of October 2016) is `importShapefileToLayer(layerName :: STRING?, uri :: STRING?)`. It takes two arguments: Whatever you would like to name the layer and a URI of where the Shapefiles are located. Validate that procedure exists then:
.. Place the folder containing all the files downloaded in step 1 in Neo4j's /bin directory. In my case the location of the directory was `/Applications/Neo4j Community Edition 2.app/Contents/Resources/app/bin`. The procedure will look for the folder of Shapefiles in the /bin directory.
.. Call the procedure passing the name of the layer and the location of the .shp file within the Shapefiles folder relative to the /bin directory. In my case the call was `CALL spatial.importShapefileToLayer("countryBorders","AFRICAandAMERICAS_LSIB4b_2012Sep04_USDoS_HIU/USDoS_LSIB4b_Africa_Americas_Sep2012.shp")`.

IMPORTANT: To be continued...

TODO::

* Create test data to prove spatial capabilities
* Issue a spatial cypher query on test data
* Incorporate into larger dataset
* Prove on a larger dataset

.stuff
. Add layer
. Add nodes to layer
.. Bulk add nodes to layer
. issue query using findGeometriesWithinDistance (or withinDistance)

NOTES::
* link:https://vimeo.com/89064528[0313 - Recommend Restaurants Near Me: Introduction to Neo4j Spatial]
* http://stackoverflow.com/questions/26560023/how-do-i-create-a-spacial-index-in-neo4j-using-only-cypher
* http://stackoverflow.com/questions/37219809/neo4j-3-0-0-spatial-in-cypher
* http://www.lyonwj.com/2016/08/09/neo4j-spatial-procedures-congressional-boundaries/
* https://hiu.state.gov/data/data.aspx
* http://trac.osgeo.org/gdal/wiki/DownloadingGdalBinaries
* http://gis.stackexchange.com/questions/7339/converting-shapefiles-to-text-ascii-files
* http://gis.stackexchange.com/questions/54870/how-to-convert-a-shapefile-to-wkt
* 
//^ 

//WARNING: These instructions are for standing up a simple, unsecure Squid instance. Secure appropriately for your context. 


////
.Configuration
. Optional, remove comments from squid.conf, `grep -Eiv '(^#|^$)' /etc/squid/squid.conf > /etc/squid/squid.conf.new`
. Set `http_port` from `3128` to `80 accel allow-direct`. This will allow Squid to proxy all HTTP traffic.
. Add the following rules. They will allow Squid to process and reply to any http traffic it receives:
.. `http_access allow all`
.. `http_reply_access allow all`

//^ 

TIP: For all the ways Squid can be configured, take advantage of link:http://wiki.squid-cache.org/[Squid's Wiki] and their link:http://www.squid-cache.org/Doc/[website's documentation] (particularly their link:http://www.squid-cache.org/Doc/config/[list of Squid configs]).

.Starting
. Enable Squid with systemctl: `systemctl enable squid`
. Start Squid: `systemctl start squid`
. Validate Squid is running by checking the processes `ps -ax | grep "squid"`
//^ 

NOTE: Changes to the squid.conf are implemented by restarting Squid ( `systemctl restart squid` )

TIP: Firefox 47.x can be configured to point all traffic to a proxy server under Preferences > Advanced > Network > Connection. Can be useful for testing Squid.

=== Optional Configurations

.Caching
. Uncomment `cache_dir ufs /var/spool/squid 100 16 256`
. Comment out all the `refresh_pattern` configs except `refresh_pattern .`

TIP: Validate Squid is properly proxying requests by tailing the access logs on the Squid server `tail -f /var/logs/squid/access.log`

NOTE: If testing using Firefox 47.x by disabling the local browser web cache by changing the amount of space allocated to the local web cache to 0mb at Preferences > Advanced > Network > Cached Web Content

.Load Balancer
. Add the following configs to squid.conf, inserting the appropriate IP or Public DNS as necessary:
.. `http_port 80 accel act-as-origin [insert primary destination server IP or Public DNS]`
.. `cache_peer [insert primary destination server IP or Public DNS] 80 0 no-query originserver round-robin`
.. `cache_peer [insert secondary destination server IP or Public DNS] parent 80 0 no-query originserver round-robin`
. Test by navigating to Squid. You should see content from one of the two destination servers. 