= Automated Testing Using Jenkins on AWS
//^

:hp-tags: AWS, Jenkins, Testing, Automated Testing, Installation, Configuration
//^

CAUTION: The following assumptions are made: You are familiar with Amazon Web Services enough to understand <<anchor-1, the first step in the Jenkins Master on AWS section>>:

=== Jenkins Master on AWS
Configure your AWS account

NOTE: I like to keep AWS from using the default for options when setting up my EC2s. It keeps me aware of the layout of my infrastructure without creating too much cruft.

[[anchor-1]]

1. Configure a VPC with an Internet Gateway and a Public Subnet. Ensure your public subnet is configured to auto-assign IP addresses. It's optional but recommended to also create an Elastic IP to associate with your Jenkins EC2. 

Install Jenkins

1. 

=== Jenkins Master creates Agents on AWS
Install Amazon EC2 Plugin

=== Jenkins Master uses Agents to Process Pipelines on AWS
Configure Amazon EC2 Plugin

=== Build a Pipeline Using a Jenkinsfile

=== Configure Jenkins to Trigger Pipelines from Github Activity

=== Going Forward