= Automated Testing Using Jenkins on AWS
//^

:hp-tags: AWS, Jenkins, Testing, Automated Testing, Installation, Configuration
//^

CAUTION: The following assumptions are made: You are familiar with Amazon Web Services enough to understand <<anchor-1, the first step in the Jenkins Master on AWS section>>:

=== Jenkins Master on AWS
Configure your AWS account

NOTE: I like to keep AWS from using the default for options when setting up my EC2s. It keeps me aware of the layout of my infrastructure without creating too much cruft.

[[anchor-1]]

1. Configure a Virtual Private Cloud with an Internet Gateway and a Public Subnet. Ensure your Public Subnet is configured to auto-assign IP addresses. It's optional but recommended to also create an Elastic IP to associate with your Jenkins EC2 (either via Network Interface or directly with the EC2 instance). 
2. Create an EC2 instance within the infrastructure created in step #1. I used a https://aws.amazon.com/marketplace/pp/B00O7WM7QW[Centos 7 AMI entitled "CentOS 7 (x86_64) - with Updates HVM)"]. 

Install Jenkins

1. 

=== Jenkins Master creates Agents on AWS
Install Amazon EC2 Plugin

=== Jenkins Master uses Agents to Process Pipelines on AWS
Configure Amazon EC2 Plugin

=== Build a Pipeline Using a Jenkinsfile

=== Configure Jenkins to Trigger Pipelines from Github Activity

=== Going Forward